# dataset
dataloader_workers: 0
dataset_path: '<SynapseCLR_repo_root>/data/MICrONS__L23__8_8_40__processed'

# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 48
dtype: 'float32'
epochs: 100

# truncate dataset (for debugging); '-1' means no truncation
dataset_head: -1

# model options
encoder_type: 'resnet18_no_max_pool'
projection_dims: [512, 128]

# optimizer options
optimizer_type: 'Adam'

# (only if "Adam" is chosen)
adam_lr: 2.0e-4

# (only if "LARS" is chosen)
weight_decay: 1.0e-6 
temperature: 0.5

# saving
checkpoint_frequency: 1
summary_frequency: 1

# reload options
checkpoint_path: '<SynapseCLR_repo_root>/output/checkpoint__synapseclr__dihedral'
reload: 1  # 0: False, 1: True
reload_optimizer_state: 1  # 0: False, 1: True
reload_epoch_num: 99

# (only for feature extraction)
feature_output_path: '<SynapseCLR_repo_root>/output/checkpoint__synapseclr__dihedral/features'
feature_extraction_hooks: [
    'encoder.fc',
    'projector.mlp.0',
    'projector.mlp.3']
    
# generate this many representations and average
# use > 1 values only if some augmentations are True in `augmenter_extract.yaml`
n_extract_augmentations: 1

# logging
loss_logging_frequency: 1  # per minibatch
extract_logging_frequency: 1  # per minibatch

# debugging
print_minibatch_indices: False
